=== adazure/panel/xsd/index.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="page">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="section" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="dropdown" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="items" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:choice maxOccurs="unbounded">
                                                    <xs:element name="item" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="label" use="required"></xs:attribute>
                                                            <xs:attribute name="data" use="required"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="media" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:attribute name="xsmall" type="xs:integer"></xs:attribute>
                                                <xs:attribute name="small" type="xs:integer"></xs:attribute>
                                                <xs:attribute name="tablet" type="xs:integer"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                    <xs:attribute name="source"></xs:attribute>
                                    <xs:attribute name="data"></xs:attribute>
                                    <xs:attribute name="multiple" type="xs:boolean" default="0"></xs:attribute>
                                    <xs:attribute name="size" type="xs:integer" default="0"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="header" minOccurs="0" maxOccurs="unbounded" />
                            <xs:element name="text" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="size" type="xs:integer" default="1"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="style" type="xs:string"></xs:attribute>
            <xs:attribute name="background" type="xs:string" default="#ffffff">
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== adazure/panel/index.xml
<?xml version="1.0" encoding="ISO-8859-9"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="xsd/index.xsd">
    <section>
        <header>Merhaba DÃ¼nya</header>
    </section>
    <section>
        <dropdown size="1">
            <media small="2"/>
            <items>
                <item label="Select Country" data="" />
                <item label="Turkey" data="turkey" />
                <item label="France" data="france" />
                <item label="Germany" data="germany" />
                <item label="Italy" data="italy" />
                <item label="Spain" data="spain" />
                <item label="England" data="englang" />
                <item label="Brazil" data="brazil" />
                <item label="Switzerland" data="switzerlang" />
                <item label="Georgia" data="georgia" />
                <item label="Moldovia" data="moldovia" />
            </items>
        </dropdown>
    </section>
</page>
